#
#This software is contributed or developed by KYOCERA Corporation.
#(C) 2012 KYOCERA Corporation
#
header-y += audio.h
header-y += cdc.h
header-y += ch9.h
header-y += ch11.h
header-y += functionfs.h
header-y += gadgetfs.h
header-y += midi.h
header-y += g_printer.h
header-y += tmc.h
header-y += f_mass_ioctl.h
